# Generated by Django 3.1.14 on 2022-05-27 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='created by')),
                ('changed_by', models.CharField(editable=False, max_length=255, verbose_name='changed by')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('languages', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'permissions': (('view_article', 'Can view article'), ('publish_article', 'Can publish article'), ('edit_static_placeholder', 'Can edit static placeholders')),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=15, verbose_name='language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('meta_description', models.TextField(blank=True, help_text='The text displayed in search engines.', null=True, verbose_name='description')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='created by')),
                ('changed_by', models.CharField(editable=False, max_length=255, verbose_name='changed by')),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(choices=[('minimal.html', 'Minimal template'), ('whitenoise-static-files-demo.html', 'Static File Demo'), ('page.html', 'Bootstrap 4 Demo'), ('feature.html', 'Bootstrap 4 Demo with two placeholders'), ('INHERIT', 'Inherit the template of the nearest ancestor')], default='minimal.html', help_text='The template used to render the content.', max_length=100, verbose_name='template')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlecontent_set', to='test_articles.article', verbose_name='article')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
