# Generated by Django 3.1.14 on 2022-06-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=255, verbose_name='name')),
                ('namespace', models.SlugField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'permissions': (('view_section', 'Can view section'), ('publish_section', 'Can publish section'), ('edit_static_placeholder', 'Can edit static placeholders')),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='languages',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_articles.section'),
        ),
    ]
